### PR TITLE
Docs/cleanup

### PR DESCRIPTION
**Pull request by rayrutjes**

### CODE REVIEW

**Comment by julienbourdeau** [comment]
I committed my update of the getting started guide (finally) 🎉

**Comment by rayrutjes** [comment]
Awesome @julienbourdeau ,

It looks like some parts still need to be adjusted a bit.
For example, I think we can merge the "autocomplete section" with the one just before.

**Comment by rayrutjes** [comment]
You think you could do a final iteration on this @julienbourdeau ? We need to deploy the pricing part because we currently reflect the old pricing which is misleading.

**Comment by julienbourdeau** [comment]
Done ✅

**Pull request merged**
