### PR TITLE
Replace getUserKeyACL (deprecated) by getApiKey

### PR DESCRIPTION
**Pull request by julienbourdeau**

### CODE REVIEW

**Comment by rayrutjes** [comment]
How comes we have changes in the API client but there is no version bump in the API client files?

**Comment by julienbourdeau** [comment]
I didn't realize that was a file in the client! 😱  I'll edit

**Comment by rayrutjes** [comment]
You can update the client by running: https://github.com/algolia/algoliasearch-wordpress/blob/master/bin/update-php-deps.sh

```
$ bin/update-php-deps.sh
```

**Comment by julienbourdeau** [comment]
The client still uses the deprecated method for the tests. I'll update it.

**Comment by rayrutjes** [comment]
Closing this for now. Feel free to re-open it when updated.

**Pull request closed without merging**
