### PR TITLE
Include marketing scripts

### PR DESCRIPTION
**Pull request by redox**

### CODE REVIEW

**Comment by rayrutjes** [comment]
It looks like the switch does not work and script gets injected even if NODE_ENV=development

**Comment by rayrutjes** [comment]
I cleaned it up a bit, that said the partial approach would probably be better in the future.
I've tested that the marketing scripts only gets added in production.

Let me know what you think @redox

**Comment by redox** [comment]
Works for me, couldn't find a smart way to do it 👍

**Comment by rayrutjes** [comment]
Thx @redox !

**Pull request merged**
