### PR TITLE
 Check if the content key was changed

### PR DESCRIPTION
**Pull request by ypantig**
Check if the content key from the shared_attributes was changed. If it is not empty, then append it to the post_content variable for indexing.

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hi @ypantig thanks for the contribution.

I see where you are going with this PR, I definitely agree there is a need to allow users to change the content attribute.

However I think it would be better to expose a new dedicated filter `algolia_searchable_posts_content` right after the `the_content` filter.

WDYT?

**Comment by ypantig** [comment]
Hey @rayrutjes, yeah, I think that would be better so there's less things to worry about if other users accidentally change another attribute value without knowing it.

**Comment by rayrutjes** [comment]
Can you check if #683 would work for you?
I'm closing this one as I kept your commits in the other branch 🎉

**Comment by ypantig** [comment]
Hi @rayrutjes, Sorry, I haven't had the chance to check #683 updates you've made yet. I'll check it out as soon as I can :)

**Pull request closed without merging**
