### PR TITLE
optimize png images using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use Google's zopflipng to re-compress the png images losslessly as below:
```
 assets/banner-1544x500.png                                | Bin 791335 -> 381463 bytes
 assets/banner-772x250.png                                 | Bin 226659 -> 126438 bytes
 assets/icon-128x128.png                                   | Bin 3968 -> 1819 bytes
 assets/icon-256x256.png                                   | Bin 8825 -> 3028 bytes
 assets/img/algolia-logo.png                               | Bin 2970 -> 1808 bytes
 assets/screenshot-1.png                                   | Bin 120172 -> 79925 bytes
 assets/screenshot-2.png                                   | Bin 104123 -> 70823 bytes
 assets/screenshot-3.png                                   | Bin 120174 -> 80068 bytes
 assets/screenshot-4.png                                   | Bin 100496 -> 68397 bytes
 assets/screenshot-5.png                                   | Bin 355792 -> 234864 bytes
 assets/screenshot-6.png                                   | Bin 1097829 -> 757637 bytes
 docs/src/img/code-block.png                               | Bin 634699 -> 332469 bytes
 docs/src/img/configuration/algolia-search-menu-entry.png  | Bin 6175 -> 4434 bytes
 docs/src/img/configuration/api-keys.png                   | Bin 197960 -> 85818 bytes
 docs/src/img/configuration/autocomplete-form-expanded.png | Bin 56253 -> 26575 bytes
 docs/src/img/configuration/autocomplete-form.png          | Bin 11810 -> 5731 bytes
 docs/src/img/configuration/autocomplete-menu.png          | Bin 13425 -> 7910 bytes
 docs/src/img/configuration/autocomplete-preview.png       | Bin 49049 -> 30780 bytes
 docs/src/img/configuration/backend-search-page.png        | Bin 79869 -> 36103 bytes
 docs/src/img/configuration/copy-button.png                | Bin 5071 -> 3669 bytes
 docs/src/img/configuration/credentials-form.png           | Bin 66386 -> 32025 bytes
 docs/src/img/configuration/index-name-prefix.png          | Bin 7201 -> 4722 bytes
 docs/src/img/configuration/indexing-validation.png        | Bin 8445 -> 5115 bytes
 docs/src/img/configuration/indices-dropdown.png           | Bin 35883 -> 19806 bytes
 docs/src/img/configuration/indices-form.png               | Bin 39947 -> 19037 bytes
 docs/src/img/configuration/menu-exanded.png               | Bin 12962 -> 7610 bytes
 docs/src/img/configuration/native-search-form.png         | Bin 105855 -> 49700 bytes
 docs/src/img/custom-attributes/re-index-everything.png    | Bin 10820 -> 8008 bytes
 docs/src/img/customize-autocomplete/custom-template.png   | Bin 88917 -> 53089 bytes
 docs/src/img/customize-autocomplete/preview.png           | Bin 167502 -> 102800 bytes
 docs/src/img/for-entrepreneurs.png                        | Bin 221798 -> 170308 bytes
 docs/src/img/for-entrepreneurs@2x.png                     | Bin 623559 -> 500607 bytes
 docs/src/img/home/wordpress-logo.png                      | Bin 8861 -> 4535 bytes
 docs/src/img/instantsearch/searchable-posts.png           | Bin 33422 -> 14914 bytes
 docs/src/img/logo-woocommerce@2x.png                      | Bin 8661 -> 5814 bytes
 docs/src/img/logs/filter-logs-display-1.png               | Bin 11023 -> 6786 bytes
 docs/src/img/og-screen.png                                | Bin 459121 -> 394018 bytes
 docs/src/img/placeholder.png                              | Bin 288913 -> 219776 bytes
 docs/src/img/preview-full.png                             | Bin 816072 -> 579099 bytes
 docs/src/img/woocommerce-ninja.png                        | Bin 13069 -> 10861 bytes
```

### CODE REVIEW

**Comment by rayrutjes** [comment]
Wow awesome @PeterDaveHello that makes sense ;)

Do you mind sharing the script? I would love to add a way to easily trigger the script.

**Comment by PeterDaveHello** [comment]
@rayrutjes :
```
zopflipng --keepchunks=iCCP --iterations=600 --lossy_transparent --splitting=3 -my origin.png new.png
```

Note that it'll take a very long time, so better not to do it on the optimized images.

**Comment by PeterDaveHello** [comment]
Zopfli: https://github.com/google/zopfli

**Comment by rayrutjes** [comment]
Ok awesome, just have to decide if we keep an original copy of the images

Are we OK keeping only the optimized images given that it is looseless compression @Shipow ?

**Comment by Shipow** [comment]
yes sure!

**Comment by PeterDaveHello** [comment]
@rayrutjes anything I need to do here ? Thanks.

**Comment by rayrutjes** [comment]
Hi don't think so @PeterDaveHello , we should be all good. I would just love to automate this optimization, and didn't find the time do do so yet.

**Comment by PeterDaveHello** [comment]
Okay, thanks, no problem!

**Comment by rayrutjes** [comment]
@PeterDaveHello I just took a look at this compression lib and the results are really impressive. But you are right it takes ages to complete, how did you manage to do 600 iterations, did you leave it running for a day? Or am I missing

Either way, I'd love to merge this instead. Can I ask you to update the PR with the last image docs/src/img/home/wordpress-logo.png to remove the conflict?

Thx a lot.

**Comment by PeterDaveHello** [comment]
@rayrutjes yes I just leave it running alone but parallel, I'm now compressing `docs/src/img/home/wordpress-logo.png` and will update the result later.

**Comment by PeterDaveHello** [comment]
All updated @rayrutjes

**Comment by rayrutjes** [comment]
Thx a lot @PeterDaveHello

**Comment by Haroenv** [comment]
I noticed that the images can be ± 60% smaller if you're using a tiny bit lower setting of zopflipng (I used 95%), which made quite a bit of difference I can't visually notice. Should I open a PR for that or is it invalid because it isn't lossless

**Comment by PeterDaveHello** [comment]
@Haroenv should better do a bit comparison rather than compare by eyes, lossy compression depends on person.

**Comment by Haroenv** [comment]
That's why I asked, this one here for example is ±500kb -> ±180kb
for-entrepreneurs 2x

**Comment by PeterDaveHello** [comment]
IMO, I won't do it on the company logos.

**Pull request merged**
