### PR TITLE
Get rid of ET Builder (Divi, Elegantthemes) Shortcodes

### PR DESCRIPTION
**Pull request by tobiasvielmetter**

### CODE REVIEW

**Comment by rayrutjes** [comment]
Thanks a lot for your patience @tobiasvielmetter !

Can you confirm that  this worked on your side?

**Comment by tobiasvielmetter** [comment]
Yes it does work. It's live on my test page https://support.wrklst.art right now and works well. Thanks

**Comment by rayrutjes** [comment]
Thanks a lot @tobiasvielmetter , this will be part of the next release.

**Comment by tobiasvielmetter** [comment]
Great, Thanks!

**Comment by tobiasvielmetter** [comment]
@rayrutjes ps: i have now switched to the official release at https://support.wrklst.art and its working like a charm. Thanks for the letting me collaborate on that issue!

**Comment by rayrutjes** [comment]
Awesome, glad it works.

Thank you for sharing this with other users!

**Pull request merged**
