### PR TITLE
Feat strip shortcodes

### PR DESCRIPTION
**Pull request by rayrutjes**
In reference to #591 

This should remove all remaining shortcodes.

@peiche could you try this out and let me know if it works for you?
@tobiasvielmetter would you mind trying out this PR to ensure that divi builder tags still gets removed properly?

Thanks a lot for your efforts!

### CODE REVIEW

**Comment by peiche** [comment]
I replaced the existing `class-algolia-utils.php` with this version and reindexed both my search page and posts indexes. I still get "aesop_" hits matching shortcodes in the autocomplete and normal search results. (I'm using Instantsearch.js for searches.)

**Comment by tobiasvielmetter** [comment]
apparently strip_shortcodes does not cover plugin shortcodes for some reason. see this polemic article for reference: https://victorfont.com/remove-divi-shortcodes-changing-themes/

I will test this next week when I find a moment.

**Comment by rayrutjes** [comment]
> apparently strip_shortcodes does not cover plugin shortcodes for some reason. see this polemic article for reference: https://victorfont.com/remove-divi-shortcodes-changing-themes/

Yes I was afraid of that. We might need to partially re-implement that function to use only the part where it tries to detect every shortcode instead of only the ones currently registered.

**Comment by tobiasvielmetter** [comment]
eventually this general regex could take care of the issue, maybe this is a little too aggressive, not sure.... https://gist.github.com/ccurtin/79fb6740bf91fb5f3db2

**Comment by rayrutjes** [comment]
Thanks for sharing that @tobiasvielmetter .

I will probably use something similar to that, and put it behind a feature flag to not affect existing users.

**Comment by rayrutjes** [comment]
We went for a safer approach, letting the user chose what patterns to remove from the content.
Please checkout #646 .

Closing this as it is no longer relevant ;)

**Pull request closed without merging**
