### PR TITLE
Applies filter to pre_get_posts

### PR DESCRIPTION
**Pull request by sebastianthulin**
Allows developers to turn on/off algolia search where they want. Would be usable when native search is desired (like in simple filter functions etc).

Example usage: 

```
    add_filter('algolia_should_filter_query', 'disableArchiveSearch', 10, 2);

    /**
     * Disables search on archive pages when searcing. Municipio requires the use of local search here.
     * @param bool $state The previous state of archive search enabler/disabler
     * @param WP_Query $query The current page query object
     * @return bool The modified toggle between algolia search on/off
     */
   function disableArchiveSearch($state, $query) : bool
    {
        if ($query->is_archive()) {
            return false;
        }
        return $state;
    }
```

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hello @sebastianthulin ,

I've nothing against this change.

Should the filter be applied on this line instead? https://github.com/helsingborg-stad/algoliasearch-wordpress/blob/ce4f0ce299e95ff2f069acf925e6253dc40ce73f/includes/class-algolia-search.php#L32

Could you split the applying of the filter on another line than the "if" statement? I think that will make things easier to read.

Could you rename your commit so that it respects conventional commit format? `feat: add algolia_should_filter_query filter`

Thanks a lot for your contribution.

**Comment by sebastianthulin** [comment]
Thank you. I initially tried to apply the filter on the suggested line, somehow i't dosen't work. If you are adding a filter on the suggested line, all querys will break for an unknown reason.

I'll make the changes that you requested.

**Comment by rayrutjes** [comment]
Hey,

I'm still not sure why this wouldn't work:

```
private function should_filter_query( WP_Query $query ) {
	$should_filter = ! $query->is_admin && $query->is_search() && $query->is_main_query();
		
        return (bool) apply_filters( 'algolia_should_filter_query', $should_filter, $query );
}
```

What kind of error do you get?

**Comment by sebastianthulin** [comment]
The error that occured was noticable when browsing the page. The front-page (may be other pages also) of the website was affected. No content was shown.

**Comment by rayrutjes** [comment]
Hello @sebastianthulin ,

I'd really like to move forward with this, unfortunately I don't have much time to dedicate.

Have you made any progress on your side?

**Comment by sebastianthulin** [comment]
Due to some commits it has been a really messy PR flow. I will close this, and reopen a simplified PR for each separate issue with descriptions.

**Pull request closed without merging**
