### PR TITLE
New landing/doc design

### PR DESCRIPTION
**Pull request by LukyVj**

### CODE REVIEW

**Comment by LukyVj** [comment]
Hey @rayrutjes I added a few improvements. Changed the github section color ( cc @redox & @Shipow ) and I added the responsive nav. 

Cheers!

**Comment by LukyVj** [comment]
- Adjust dark pattern background
- Adjust anchor trick

**Comment by rayrutjes** [comment]
Could we hide the 'wordpress plugin' on mobile? It currently overlaps the mobile dropdown nav:
image

I would reduce the bottom padding a bit on the homepage here, nothing critical though:
image


Looks great!!!

**Comment by LukyVj** [comment]
Yeah leave it like this for now, i'll do an other PR asap.

**Comment by rayrutjes** [comment]
Thank you @LukyVj

**Pull request merged**
