### PR TITLE
Add plugin directory images

### PR DESCRIPTION
**Pull request by rayrutjes**
Resolves: #231 

/cc @redox @AntoinePlu

### CODE REVIEW

**Comment by redox** [comment]
Should we include a small preview of the autocompletion menu & search bar so we get it's about search? I'm afraid it's very difficult to understand what those icons are.

**Comment by rayrutjes** [comment]
Yes we should probably make it more obvious. We should either add some kind of magnifier, or a screen of the search bar. What do you think of using the community guy?
image

**Comment by redox** [comment]
> What do you think of using the community guy?

No I won't go for the Alien, too "fun" for the extension. Rather put the Algolia community logo.

**Comment by rayrutjes** [comment]
Owe yeah the community logo would be sweet, could you handle that @AntoinePlu when you have some time?

Also, I like this header which makes it very obvious:
image

**Comment by rayrutjes** [comment]
We also need to integrate these visuals on the community page, they are gorgeous and very explicit. Do we have them without background?

**Pull request merged**
