### PR TITLE
Allow hook to change behavior

### PR DESCRIPTION
**Pull request by Horrower**
For support is_archive() pages

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hi @Horrower ,

Unless I'm missing something, I don't see any change coming from this PR.

**Comment by Horrower** [comment]
public function should_override_search_with_instantsearch() {
		$value = $this->get_override_native_search() === 'instantsearch';

		return (bool) apply_filters( 'algolia_should_override_search_with_instantsearch', $value );
	}


you have hook in "should_override_search_with_instantsearch"

**Comment by rayrutjes** [comment]
In the PR you just inverted the elements inside an && condition.
So unless you are relying on the side effects of `should_override_search_with_instantsearch` it doesn't change much.


Could you provide your solution so that I can better understand?

**Comment by Horrower** [comment]
I'v changed it to 
``` 
if ( $settings->should_override_search_with_instantsearch() && (is_search() || is_archive() )  ) {
```
actually. but this must be refactored to allow developers to control which pages should be allowed to do instant search.
in my example I want to enable in on all archive pages: tags, categories, etc. 
Do you understand? My code is just temporary solution

**Comment by rayrutjes** [comment]
I'm closing this for now given the PR brings no behaviour change for now. Feel free to re-submit a new PR if needed.
For now, instantsearch is only to be displayed on the search page and we do not support displaying it on other pages. If you want to do so, you can definitely inject the instantsearch.js library in other pages and do a custom implementation even re-using existing indices.

**Comment by Horrower** [comment]
I will provide a working version later

**Pull request closed without merging**
