### PR TITLE
Push urls of all thumbnail sizes

### PR DESCRIPTION
**Pull request by rayrutjes**
Resolves: #218

### CODE REVIEW

**Comment by redox** [comment]
Should we also add a `default` size (`thumbnail.default: {...}`) to ease the implementations?

**Comment by rayrutjes** [comment]
I have left the `thumbnail_url` attribute for backward compatibility purposes which can be used for that maybe, but we have no idea of sizes there.

Nevertheless, the default thumbnail is called `thumbnail ` which by default is a 150x150 picture according to: https://codex.wordpress.org/Post_Thumbnails

Just wondering if we should take the opportunity to remove the `thumbnail_url` and refactor the templates while we are at it.

Not sure it is that complex to write `data.thumbnails.thumbnail.url`.

Let me know what you think @redox .

**Comment by rayrutjes** [comment]
@redox I'm going to merge it as is because it doesn't introduce any BC issue, but lets continue this discussion if needed in an issue.

**Comment by redox** [comment]
> Not sure it is that complex to write data.thumbnails.thumbnail.url.

Oh ok, so it means we have all images there, not only thumbnails? Then maybe having a `images` attribute instead of `thumbnails` so it ends up with `data.images.thumbnail.url`?

And yes, better to break the record schema now :)

**Pull request merged**
