### PR TITLE
Add filter algolia_search_params

### PR DESCRIPTION
**Pull request by SiR-DanieL**
Adding filter `algolia_search_params` to allow changes before to search in Algolia.

This would allow us to add custom attributes to the search params.

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hi @SiR-DanieL , thanks a lot for contributing ;)

This was suggested in the past, and I'm not sure it is a good idea but at the same time I understand it's need.

1. It is not a good idea because if we mess with the pagination param it will break the pagination in the UI
2. I get that you want to filter out some post types for example

Could you share your specific use case?

**Comment by SiR-DanieL** [comment]
The specific use case is that we need to add faceting and optional faceting to the results. This way we could get better results.

Maybe you can add indexes for that only in the array and allow filtering on that?

**Comment by rayrutjes** [comment]
I think this PR is OK, developers will just need to make sure to know what they are doing ;)

Thanks a lot!

**Comment by rayrutjes** [comment]
@SiR-DanieL 1.4.0 is out, please update ;)

**Pull request merged**
