### PR TITLE
Shim support for WPML

### PR DESCRIPTION
**Pull request by insanetisane**
https://github.com/algolia/algoliasearch-wordpress/issues/454#issuecomment-277612895

### CODE REVIEW

**Comment by rayrutjes** [comment]
Thanks for sharing this @insanetisane ,

I will try to refactor this piece of code in the compatibility class and leave this open until then.

**Comment by rayrutjes** [comment]
After some investigation, there seem to be an easier approach to this:
https://gist.github.com/rayrutjes/5f51dc9e306da5d82dc5363a3e0507a7

This will make sure anything happening  with the post will only take info of the correct language.

I'm closing this for now, and will document a solution using the new approach.

**Comment by insanetisane** [comment]
@rayrutjes That's great! I look forward to seeing how to implement this on my end. Thanks for your help with this! Much appreciated!

**Comment by rayrutjes** [comment]
Here is the PR #527 it should work out of the box in the new release.

**Pull request closed without merging**
