### PR TITLE
Make autocomplete easier to customize

### PR DESCRIPTION
**Pull request by rayrutjes**
Resolves: #203

### CODE REVIEW

**Comment by rayrutjes** [comment]
@redox I'd appreciate if you could take a quick look. A lot going on here. I have tested most of it.

Still need to:
- [ ] Test the template overriding logic
- [ ] Update docs

**Comment by redox** [comment]
@rayrutjes just tested it locally. Works great 👍

**Comment by rayrutjes** [comment]
I'm am running in some conflicts when enabling W3 Total Cache, will try to fix is before merging.

**Comment by rayrutjes** [comment]
As discussed, underscore escapes `& < > " ' /` chars  by default when using the {{}} syntax, so we are good there.

I think we are good for this PR as it is already huge ;)

**Comment by rahilwazir** [comment]
@rayrutjes @redox Thanks for embeding JS to the template. I really wanted to customize that as well. :+1:

**Comment by redox** [comment]
> @rayrutjes @redox Thanks for embedding JS to the template. I really wanted to customize that as well. 👍

Yeah, much simpler like that :) Thanks for the feedback 💯

**Pull request merged**
