### PR TITLE
chore(readme): adjust pricing mention

### PR DESCRIPTION
**Pull request by rayrutjes**

### CODE REVIEW

**Comment by dzello** [comment]
@rayrutjes Cool! Do we want to also update the pricing minimum from $49/mo to $35/mo?

**Comment by rayrutjes** [comment]
What do you think @dzello ? No opinion here, I can add it if you want. Let me know.

**Comment by dzello** [comment]
@rayrutjes Yeah, I think it's worth it

**Comment by rayrutjes** [comment]
I adjusted the text ;)

**Pull request merged**
