### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by Fastbyte01**
Italian translation added.

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hi there,

Thanks a lot for submitting this.
We tried to leverage the official tool for translations [in the past](https://github.com/algolia/algoliasearch-wordpress/pull/390) without success.

I just took a look and it appears I narrowed down the issue.
Give me some time to fix our language file.

**Comment by rayrutjes** [comment]
Any chance you could submit your pot here: https://translate.wordpress.org/projects/wp-plugins/search-by-algolia-instant-relevant-results ?

**Comment by Fastbyte01** [comment]
Yes, sure.

2017-10-09 14:44 GMT+02:00 Raymond Rutjes <notifications@github.com>:

**Comment by rayrutjes** [comment]
Thanks @Fastbyte01 , TBH I'm not really sure about the process here.
I'll have to spend some time figuring out the best what to share your work.

Let me know if you are knowledgable on the subject.
Maybe I can summon @Mamaduka on this one 😛 .

**Comment by Fastbyte01** [comment]
@rayrutjes But on Glotpress seems that there is only the readme file and not the translations of the plugin, as there is on Github. The strings to translate are all different.

**Comment by rayrutjes** [comment]
I got to dive in the [handbook](https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/) to figure this out properly.

**Comment by rayrutjes** [comment]
I think we can merge it as is.
@proudlygeek , would you mind taking a quick look at @Fastbyte01 work?

**Comment by rayrutjes** [comment]
Looks good to you @proudlygeek ? 🇮🇹

**Comment by Fastbyte01** [comment]
@proudlygeek thanks, typos and grammar error fixed. @rayrutjes Updated the pull request. Now is OK.

**Comment by rayrutjes** [comment]
This has been merged here: https://github.com/algolia/algoliasearch-wordpress/pull/678

Thanks a lot @Fastbyte01 .
We took this as an opportunity to fix our i18n support.

I kept your original commit ;)

**Comment by Fastbyte01** [comment]
@rayrutjes You can try to use a solution like transifex. In this way for some people can be more simple to help you translate the project.

**Pull request closed without merging**
