### PR TITLE
fallback fonts in facets-illus.svg

### PR DESCRIPTION
**Pull request by Haroenv**
This image didn't have any fallback font for when Open Sans isn't loaded/installed, there should be a fallback font

this is also fixed by using outlines

feel free to close if you decide to use another strategy

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hi @Haroenv , thanks a lot for the PR!

@LukyVj @Shipow would you guys mind taking a look at it?

**Comment by LukyVj** [comment]
Sure, will do

**Comment by LukyVj** [comment]
So, I wont merge the PR since the output SVG looks different than the original one : 

| Before        | After           |
| ------------- |:-------------:|
|  |  |


I will outline the text in the svgs to fix the font problem.

**Comment by Haroenv** [comment]
Makes sense. I never saw the original

**Pull request closed without merging**
