### PR TITLE
Made the instantsearch widgets translatable

### PR DESCRIPTION
**Pull request by royduin**

### CODE REVIEW

**Comment by rayrutjes** [comment]
Wow, thanks @royduin for contributing again!

We would love to make this part translatable. That being said we don't want to mix PHP and JS in that file so that users can very easily extract the JS in a separated static JS file.

Maybe the best here would be to add a "translations" key to the "algolia" config.

Here is where I'm thinking we could inject it: https://github.com/algolia/algoliasearch-wordpress/blob/master/includes/class-algolia-template-loader.php#L35

What do you think?

**Comment by royduin** [comment]
I think it's not a problem because there is already a lot of language mixes in the `instantsearch.php` file there is PHP, HTML and JS. If you want to do it clean all those languages should be separated...

**Comment by rayrutjes** [comment]
> I think it's not a problem because there is already a lot of language mixes in the instantsearch.php file there is PHP, HTML and JS. If you want to do it clean all those languages should be separated...

Agreed that separating languages would make it cleaner, but from our experience it would also make it harder for our users to customize it.

I would go for the suggested approach, but will spend some time thinking about it.

**Comment by royduin** [comment]
Shall I create another commit with that new approach? Or do you want to discuss this more before you accept this pull request or create another implementation?

**Comment by rayrutjes** [comment]
I don't want you to work for nothing we we decide to move on with your approach.
The Pro of what I had in mind is that developers will be able to extract the code in a separated JS file and still be able to leverage the translations.

Otherwise they will need to re-implement that part on their own.

**Comment by rayrutjes** [comment]
So eventually the translations will need to be provided by the backend and not be mixed with JS frontend code.

The best would be to use the WordPress wp_localize_script method.

I'm closing this for now and will try to implement a version using that method in the future.

As a workaround for now, users can override the template to achieve translations.

**Pull request closed without merging**
