### PR TITLE
feat(autocomplete): dropdown menu improvements

### PR DESCRIPTION
**Pull request by redox**
- make sure the dropdown width fits the input width
 - display the snippeted content by default
 - CSS cleanup

screen shot 2016-08-01 at 17 08 32

### CODE REVIEW

**Comment by redox** [comment]
I tried to improve a bit the default look & feel of the dropdown menu; I think it's already better but I'm still concerned by the display of the posts without images.

**Comment by rayrutjes** [comment]
Looks definitely better already. Will try to compute your work with some of the work available here: https://community.algolia.com/wordpress/customize-autocomplete.html

**Comment by rayrutjes** [comment]
image

I think we should maybe keep the tether repositioning trick and put a min width for cases where the search input is small.

**Comment by redox** [comment]
LGTM @rayrutjes 👍

**Pull request merged**
